In [20]:
import numpy as np
import pandas as pd

In [21]:
movies=pd.read_csv("imdb-top-1000.csv")

In [22]:
movies.head(1)

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0

In [23]:
genres=movies.groupby("Genre")

In [24]:
genres.min()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,300,1924,45,7.6,Abhishek Chaubey,Aamir Khan,25312,3296.0,33.0
Adventure,2001: A Space Odyssey,1925,88,7.6,Akira Kurosawa,Aamir Khan,29999,61001.0,41.0
Animation,Akira,1940,71,7.6,Adam Elliot,Adrian Molina,25229,128985.0,61.0
Biography,12 Years a Slave,1928,93,7.6,Adam McKay,Adrien Brody,27254,21877.0,48.0
Comedy,(500) Days of Summer,1921,68,7.6,Alejandro G. Iñárritu,Aamir Khan,26337,1305.0,45.0
Crime,12 Angry Men,1931,80,7.6,Akira Kurosawa,Ajay Devgn,27712,6013.0,47.0
Drama,1917,1925,64,7.6,Aamir Khan,Abhay Deol,25088,3600.0,28.0
Family,E.T. the Extra-Terrestrial,1971,100,7.8,Mel Stuart,Gene Wilder,178731,4000000.0,67.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,7.9,F.W. Murnau,Max Schreck,57428,337574718.0,NaN
Film-Noir,Shadow of a Doubt,1941,100,7.8,Alfred Hitchcock,Humphrey Bogart,59556,449191.0,94.0
Horror,Alien,1933,71,7.6,Alejandro Amenábar,Anthony Perkins,27007,89029.0,46.0
Mystery,Dark City,1938,96,7.6,Alex Proyas,Bernard-Pierre Donnadieu,33982,1035953.0,52.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1965,132,7.8,Clint Eastwood,Clint Eastwood,65659,5321508.0,69.0

In [25]:
genres.mean()

/var/folders/g7/n796cwkn2w17m4qhymxv0zr00000gn/T/ipykernel_11730/1248226035.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  genres.mean()

              Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     129.046512     7.949419  420246.581395  1.897224e+08  73.419580
Adventure  134.111111     7.937500  313557.819444  1.319017e+08  78.437500
Animation   99.585366     7.930488  268032.073171  1.784326e+08  81.093333
Biography  136.022727     7.938636  272805.045455  9.404952e+07  76.240506
Comedy     112.129032     7.901290  178195.658065  1.010572e+08  78.720000
Crime      126.392523     8.016822  313398.271028  7.899656e+07  77.080460
Drama      124.737024     7.957439  212343.612457  1.225259e+08  79.701245
Family     107.500000     7.800000  275610.500000  2.195553e+08  79.000000
Fantasy     85.000000     8.000000   73111.000000  3.913633e+08        NaN
Film-Noir  104.000000     7.966667  122405.000000  4.197018e+07  95.666667
Horror     102.090909     7.909091  340232.363636  9.405902e+07  80.000000
Mystery    119.083333     7.975000  350250.333333  1.047014e+08  79.125000
Thriller   108.000000     7.800000   27733.000000  1.755074e+07  81.000000
Western    148.250000     8.350000  322416.250000  1.455538e+07  78.250000

In [26]:
genres.std()

/var/folders/g7/n796cwkn2w17m4qhymxv0zr00000gn/T/ipykernel_11730/4044499807.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  genres.std()

             Runtime  IMDB_Rating    No_of_Votes         Gross  Metascore
Genre
Action     28.500706     0.304258  432946.814748  2.256724e+08  12.421252
Adventure  33.317320     0.229781  301188.347642  1.697543e+08  12.345393
Animation  14.530471     0.253221  262173.231571  2.091840e+08   8.813646
Biography  25.514466     0.267140  271284.191372  1.363251e+08  11.028187
Comedy     22.946213     0.228771  188653.570564  1.946513e+08  11.829160
Crime      27.689231     0.335477  373999.730656  1.571191e+08  13.099102
Drama      27.740490     0.267229  305554.162841  2.201164e+08  12.744687
Family     10.606602     0.000000  137008.302816  3.048412e+08  16.970563
Fantasy    12.727922     0.141421   22179.111299  7.606861e+07        NaN
Film-Noir   4.000000     0.152753   54649.083277  7.048472e+07   1.527525
Horror     13.604812     0.311302  234883.508691  9.965017e+07  15.362291
Mystery    14.475423     0.310791  404621.915297  1.567524e+08  18.604435
Thriller         NaN          NaN            NaN           NaN        NaN
Western    17.153717     0.420317  263489.554280  1.230626e+07   9.032349

In [28]:
movies.groupby("Genre")["IMDB_Rating"].mean().sort_values(ascending=False)

Genre
Western      8.350000
Crime        8.016822
Fantasy      8.000000
Mystery      7.975000
Film-Noir    7.966667
Drama        7.957439
Action       7.949419
Biography    7.938636
Adventure    7.937500
Animation    7.930488
Horror       7.909091
Comedy       7.901290
Family       7.800000
Thriller     7.800000
Name: IMDB_Rating, dtype: float64

In [42]:
movies.groupby("Director")["No_of_Votes"].sum().sort_values(ascending=False)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
David Fincher         6607859
Martin Scorsese       6513530
                       ...
J. Lee Thompson         26457
Peter Mullan            25938
René Laloux             25229
Francis Lee             25198
Kaige Chen              25088
Name: No_of_Votes, Length: 548, dtype: int64

In [50]:
movies.groupby("Star1")["Series_Title"].count().sort_values(ascending=False)

Star1
Tom Hanks             12
Robert De Niro        11
Clint Eastwood        10
Al Pacino             10
Leonardo DiCaprio      9
                      ..
Glen Hansard           1
Giuseppe Battiston     1
Giulietta Masina       1
Gerardo Taracena       1
Ömer Faruk Sorak       1
Name: Series_Title, Length: 660, dtype: int64